
name: 'retail_dbt_project'
version: '1.0'
profile: 'retail_mysql'
models:
  retail_dbt_project:
    staging:
      materialized: view
    intermediate:
      materialized: view
    marts:
      materialized: table
