
retail_mysql:
  target: dev
  outputs:
    dev:
      type: mysql
      server: "{{ env_var('DB_HOST', '127.0.0.1') }}"
      port: 3306
      user: "{{ env_var('DB_USER', 'root') }}"
      password: "{{ env_var('DB_PASSWORD', '') }}"
      schema: "{{ env_var('DB_NAME', 'retail_analytics') }}"
