version: 2

sources:
  - name: retail_analytics
    database: retail_analytics
    schema: retail_analytics
    tables:
      - name: stg_sales
      - name: stg_stores
      - name: stg_features
      - name: stream_sales_events 