version: 2

sources:
  - name: retail_analytics
    database: retail_analytics
    schema: retail_analytics
    tables:
      - name: raw_sales
      - name: raw_stores
      - name: raw_features
      - name: stream_sales_events 